CREATE TABLE VND_T1 (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR(20)
);

INSERT INTO VND_T1 VALUES (10, 'Andrey');
INSERT INTO VND_T1 VALUES (11, 'Dmitry');
INSERT INTO VND_T1 VALUES (12, 'Nick');
COMMIT;

SELECT * FROM VND_T1;

DROP TABLE VND_T1;

SELECT * FROM USER_RECYCLEBIN;

FLASHBACK TABLE VND_T1 TO BEFORE DROP;

begin
FOR loopIndex IN 0..99999
LOOP
   INSERT INTO VND_T1 VALUES (loopIndex + 20, 'NAME');
END LOOP;
COMMIT;
end;

SELECT COUNT(*) FROM VND_T1;

SELECT ID, ROWID, ORA_ROWSCN FROM VND_T1
    ORDER BY ID
    FETCH FIRST 10 ROWS ONLY;

DROP TABLE VND_T1;

CREATE TABLE VND_T1 (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR(20)
) ROWDEPENDENCIES;