ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER VNDS
    IDENTIFIED BY pass
    ACCOUNT UNLOCK;
    
GRANT
    CREATE SESSION,
    CREATE TABLE
    TO VNDS;
    
SELECT DEFAULT_TABLESPACE FROM DBA_USERS WHERE USERNAME = 'VNDS';

ALTER USER VNDS QUOTA 100M ON USERS;
    
--DROP USER VNDS;