CREATE TABLE VNDS.T_RANGE (
    ID NUMBER,
    NAME VARCHAR(20)
)
PARTITION BY RANGE (ID)
(
    PARTITION p_range_100 VALUES LESS THAN (100),
    PARTITION p_range_200 VALUES LESS THAN (200),
    PARTITION p_range_300 VALUES LESS THAN (300),
    PARTITION p_range_400 VALUES LESS THAN (400)
);

CREATE TABLE VNDS.T_INTERVAL (
    ID NUMBER,
    ORDER_DETAILS VARCHAR(50),
    ORDER_DATE DATE 
)
PARTITION BY RANGE (ORDER_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION p0 VALUES LESS THAN (TO_DATE('01-JAN-2023', 'DD-MON-YYYY'))
);

CREATE TABLE VNDS.T_HASH (
    NAME VARCHAR2(20),
    PHONE VARCHAR2(20)
)
PARTITION BY HASH (NAME)
PARTITIONS 4;

CREATE TABLE VNDS.T_LIST (
    OFFICE VARCHAR2(50),
    REGION CHAR(2)
)
PARTITION BY LIST (REGION)
(
    PARTITION p_list_us VALUES ('US'),
    PARTITION p_list_eu VALUES ('EU'),
    PARTITION p_list_by VALUES ('BY'),
    PARTITION p_others VALUES (DEFAULT)
);

INSERT INTO VNDS.T_RANGE (ID, NAME) VALUES (50, 'Name 1');
INSERT INTO VNDS.T_RANGE (ID, NAME) VALUES (150, 'Name 2');
INSERT INTO VNDS.T_RANGE (ID, NAME) VALUES (250, 'Name 3');
INSERT INTO VNDS.T_RANGE (ID, NAME) VALUES (350, 'Name 4');

--DROP TABLE VNDS.T_LIST;
--DROP TABLE VNDS.T_HASH;
--DROP TABLE VNDS.T_INTERVAL;
--DROP TABLE VNDS.T_RANGE;