SELECT ROUND(SUM(VALUE)/1024/1024, 2) MB FROM V$SGA;

SELECT COMPONENT, ROUND(CURRENT_SIZE/1024/1024, 2) MB, GRANULE_SIZE FROM V$SGA_DYNAMIC_COMPONENTS;

SELECT ROUND(SUM(BYTES)/1024/1024, 2) MB FROM V$SGASTAT
    WHERE NAME = 'free memory';
    
SHOW PARAMETER SGA;

--7-8

SHOW PARAMETER LOG_BUFFER;

SELECT ROUND(SUM(BYTES)/1024/1024, 2) MB FROM V$SGASTAT
    WHERE NAME = 'free memory'
    AND   POOL = 'large pool';
    
SELECT USERNAME, SID, SERIAL#, SERVER, STATUS FROM V$SESSION WHERE USERNAME IS NOT NULL;

SELECT NAME, DESCRIPTION FROM V$BGPROCESS;
    
SELECT PNAME, USERNAME FROM V$PROCESS
    WHERE BACKGROUND IS NULL;
    
SELECT COUNT(*) DBW_PROCESSES FROM V$BGPROCESS
    WHERE DESCRIPTION LIKE '%db writer%';
    
SELECT NAME, NETWORK_NAME FROM V$SERVICES;

SHOW PARAMETER DISPATCHER;

--docker exec -it oracledb lsnrctl status

--docker exec -t -i oracledb /bin/bash
--/opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora

--docker exec -it oracledb lsnrctl

--docker exec -it oracledb lsnrctl services