SELECT ROUND(SUM(VALUE)/1024/1024, 2) MB FROM V$SGA;

SELECT COMPONENT, ROUND(CURRENT_SIZE/1024/1024, 2) MB, GRANULE_SIZE FROM V$SGA_DYNAMIC_COMPONENTS;

SELECT ROUND(SUM(BYTES)/1024/1024, 2) MB FROM V$SGASTAT
    WHERE NAME = 'free memory';
    
SHOW PARAMETER SGA;

SHOW PARAMETER KEEP;

CREATE TABLE T_KEEP (ID NUMBER);

INSERT INTO T_KEEP VALUES (10);
INSERT INTO T_KEEP VALUES (10);
INSERT INTO T_KEEP VALUES (10);
COMMIT;

ALTER SYSTEM SET DB_KEEP_CACHE_SIZE = 2M SCOPE = MEMORY;

ALTER TABLE T_KEEP STORAGE (BUFFER_POOL KEEP);

SELECT SEGMENT_NAME, BUFFER_POOL FROM DBA_SEGMENTS
    WHERE SEGMENT_NAME = 'T_KEEP';
    
CREATE TABLE T_DEFAULT (ID NUMBER);

SELECT SEGMENT_NAME, BUFFER_POOL FROM DBA_SEGMENTS
    WHERE SEGMENT_NAME = 'T_DEFAULT';

SHOW PARAMETER LOG_BUFFER;

SELECT ROUND(SUM(BYTES)/1024/1024, 2) MB FROM V$SGASTAT
    WHERE NAME = 'free memory'
    AND   POOL = 'large pool';
    
SELECT USERNAME, SID, SERIAL#, SERVER, STATUS FROM V$SESSION WHERE USERNAME IS NOT NULL;

SELECT NAME, DESCRIPTION FROM V$BGPROCESS;
    
SELECT PNAME, USERNAME FROM V$PROCESS
    WHERE BACKGROUND IS NULL;
    
SELECT COUNT(*) DBW_PROCESSES FROM V$BGPROCESS
    WHERE DESCRIPTION LIKE '%db writer%';
    
SELECT NAME, NETWORK_NAME FROM V$SERVICES;

SHOW PARAMETER DISPATCHER;

--docker exec -it oracledb lsnrctl status

--docker exec -t -i oracledb /bin/bash
--/opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora

--docker exec -it oracledb lsnrctl

--docker exec -it oracledb lsnrctl services

--DROP TABLE T_KEEP;
--DROP TABLE T_DEFAULT;