CREATE TABLE VNDS.T_RANGE (
    ID NUMBER,
    NAME VARCHAR(20)
)
PARTITION BY RANGE (ID)
(
    PARTITION p_range_100 VALUES LESS THAN (100),
    PARTITION p_range_200 VALUES LESS THAN (200),
    PARTITION p_range_300 VALUES LESS THAN (300),
    PARTITION p_range_400 VALUES LESS THAN (400)
);

CREATE TABLE VNDS.T_INTERVAL (
    ID NUMBER,
    ORDER_DETAILS VARCHAR(50),
    ORDER_DATE DATE 
)
PARTITION BY RANGE (ORDER_DATE)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION p0 VALUES LESS THAN (TO_DATE('01-JAN-2023', 'DD-MON-YYYY'))
);

CREATE TABLE VNDS.T_HASH (
    NAME VARCHAR2(20),
    PHONE VARCHAR2(20)
)
PARTITION BY HASH (NAME)
PARTITIONS 4;

CREATE TABLE VNDS.T_LIST (
    OFFICE VARCHAR2(50),
    REGION CHAR(2)
)
PARTITION BY LIST (REGION)
(
    PARTITION p_list_us VALUES ('US'),
    PARTITION p_list_eu VALUES ('EU'),
    PARTITION p_list_by VALUES ('BY'),
    PARTITION p_list_others VALUES (DEFAULT)
);

INSERT INTO VNDS.T_RANGE (ID, NAME) VALUES (50, 'Name 1');
INSERT INTO VNDS.T_RANGE (ID, NAME) VALUES (150, 'Name 2');
INSERT INTO VNDS.T_RANGE (ID, NAME) VALUES (250, 'Name 3');
INSERT INTO VNDS.T_RANGE (ID, NAME) VALUES (350, 'Name 4');

INSERT INTO VNDS.T_INTERVAL (ID, ORDER_DETAILS, ORDER_DATE)
VALUES (1, 'Order details', TO_DATE('15-APR-2022', 'DD-MON-YYYY'));
INSERT INTO VNDS.T_INTERVAL (ID, ORDER_DETAILS, ORDER_DATE)
VALUES (2, 'Order details', TO_DATE('20-MAY-2022', 'DD-MON-YYYY'));
INSERT INTO VNDS.T_INTERVAL (ID, ORDER_DETAILS, ORDER_DATE)
VALUES (3, 'Order details', TO_DATE('15-JUN-2022', 'DD-MON-YYYY'));
INSERT INTO VNDS.T_INTERVAL (ID, ORDER_DETAILS, ORDER_DATE)
VALUES (4, 'Order details', TO_DATE('10-JUL-2022', 'DD-MON-YYYY'));

INSERT INTO VNDS.T_HASH (NAME, PHONE)
VALUES ('John Doe', '123-456-7890');
INSERT INTO VNDS.T_HASH (NAME, PHONE)
VALUES ('Jane Doe', '234-567-8901');
INSERT INTO VNDS.T_HASH (NAME, PHONE)
VALUES ('Bob Smith', '345-678-9012');
INSERT INTO VNDS.T_HASH (NAME, PHONE)
VALUES ('Alice Smith', '456-789-0123');

INSERT INTO VNDS.T_LIST (OFFICE, REGION)
VALUES ('New York Office', 'US');
INSERT INTO VNDS.T_LIST (OFFICE, REGION)
VALUES ('London Office', 'EU');
INSERT INTO VNDS.T_LIST (OFFICE, REGION)
VALUES ('Minsk Office', 'BY');
INSERT INTO VNDS.T_LIST (OFFICE, REGION)
VALUES ('Sydney Office', 'AU');

SELECT * FROM T_RANGE PARTITION (p_range_100);
SELECT * FROM T_RANGE PARTITION (p_range_200);
SELECT * FROM T_RANGE PARTITION (p_range_300);
SELECT * FROM T_RANGE PARTITION (p_range_400);
SELECT * FROM T_LIST PARTITION (p_list_us);
SELECT * FROM T_LIST PARTITION (p_list_eu);
SELECT * FROM T_LIST PARTITION (p_list_by);
SELECT * FROM T_LIST PARTITION (p_list_others);
SELECT PARTITION_NAME
    FROM USER_TAB_PARTITIONS
    WHERE TABLE_NAME = 'T_HASH';
SELECT PARTITION_NAME, HIGH_VALUE
    FROM USER_TAB_PARTITIONS
    WHERE TABLE_NAME = 'T_INTERVAL';
    
ALTER TABLE T_RANGE ENABLE ROW MOVEMENT;
UPDATE T_RANGE 
    SET ID = ID + 80
    WHERE ID = 50;

ALTER TABLE T_HASH ENABLE ROW MOVEMENT; 
UPDATE T_HASH
    SET NAME = 'New Name'
    WHERE NAME = 'John Doe';

ALTER TABLE T_INTERVAL ENABLE ROW MOVEMENT; 
UPDATE T_INTERVAL
    SET ORDER_DATE = ADD_MONTHS(ORDER_DATE, 1)
    WHERE ID = 2;

ALTER TABLE T_LIST ENABLE ROW MOVEMENT; 
UPDATE T_LIST
    SET REGION = 'US'
    WHERE REGION = 'EU';
    
ALTER TABLE T_RANGE MERGE PARTITIONS
    p_range_100, p_range_200 INTO PARTITION p_range_100_200;
    
SELECT PARTITION_NAME, HIGH_VALUE
    FROM USER_TAB_PARTITIONS
    WHERE TABLE_NAME = 'T_RANGE';
    
ALTER TABLE T_RANGE SPLIT PARTITION 
    p_range_100_200
    AT (100)
    INTO (PARTITION p_range_100,
    PARTITION p_range_200);

SELECT PARTITION_NAME, HIGH_VALUE
    FROM USER_TAB_PARTITIONS
    WHERE TABLE_NAME = 'T_RANGE';

CREATE TABLE VNDS.T_PARTITION (
    OFFICE VARCHAR2(50),
    REGION CHAR(2)
);

ALTER TABLE T_LIST EXCHANGE PARTITION
    p_list_us
    WITH TABLE T_PARTITION
    WITHOUT VALIDATION;
    
SELECT * FROM T_LIST;
SELECT * FROM T_PARTITION;
    
--DROP TABLE VNDS.T_LIST;
--DROP TABLE VNDS.T_HASH;
--DROP TABLE VNDS.T_INTERVAL;
--DROP TABLE VNDS.T_RANGE;