ALTER SESSION SET "_oracle_script" = TRUE;

CREATE ROLE RL_VNDCORE;

GRANT CREATE SESSION,
      CREATE TABLE,
      CREATE VIEW,
      CREATE PROCEDURE
      TO RL_VNDCORE;

SELECT * FROM DBA_ROLES WHERE ROLE = 'RL_VNDCORE';
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_VNDCORE';

CREATE PROFILE PF_VNDCORE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;
    
SELECT DISTINCT PROFILE FROM DBA_PROFILES;
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_VNDCORE';
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

CREATE USER VNDCORE 
    IDENTIFIED BY pass
    DEFAULT TABLESPACE TS_VND
    TEMPORARY TABLESPACE TS_VND_TEMP
    PROFILE PF_VNDCORE
    ACCOUNT UNLOCK
    PASSWORD EXPIRE;
GRANT RL_VNDCORE TO VNDCORE;

--DROP USER VNDCORE CASCADE;
--DROP PROFILE PF_VNDCORE;
--DROP ROLE RL_VNDCORE;