ALTER SESSION SET "_oracle_script" = TRUE;

CREATE TABLESPACE TS_VND
    DATAFILE 'TS_VND.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 30M;
    
CREATE TEMPORARY TABLESPACE TS_VND_TEMP
    TEMPFILE 'TS_VND_TEMP.dbf'
    SIZE 5M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 20M;
    
SELECT TABLESPACE_NAME, STATUS, contents logging FROM SYS.DBA_TABLESPACES;
SELECT FILE_NAME, TABLESPACE_NAME, STATUS FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME, STATUS FROM DBA_TEMP_FILES;
    
--DROP TABLESPACE TS_VND INCLUDING CONTENTS AND DATAFILES;
--DROP TABLESPACE TS_VND_TEMP INCLUDING CONTENTS AND DATAFILES;