SELECT PDB_NAME, PDB_ID, STATUS FROM DBA_PDBS;

ALTER SESSION SET CONTAINER = VND_PDB;
SHOW CON_NAME;

GRANT CREATE SESSION TO C##VND CONTAINER = CURRENT;

SELECT * FROM CDB_TABLESPACES;
SELECT * FROM CDB_DATA_FILES;
SELECT * FROM CDB_TEMP_FILES;
SELECT * FROM CDB_ROLES;
SELECT * FROM CDB_PROFILES;
SELECT * FROM CDB_USERS;
SELECT * FROM CDB_SYS_PRIVS;

SELECT USERNAME, SID, STATUS FROM V$SESSION WHERE USERNAME IS NOT NULL;

SELECT OBJECT_NAME FROM ALL_OBJECTS;
