ALTER PLUGGABLE DATABASE VND_PDB OPEN;
ALTER SESSION SET CONTAINER = VND_PDB;

CREATE USER VND 
    IDENTIFIED BY pass
    DEFAULT TABLESPACE TS_VND
    TEMPORARY TABLESPACE TS_VND_TEMP
    ACCOUNT UNLOCK;
    
GRANT CREATE SESSION,
      CREATE TABLE,
      CREATE SEQUENCE,
      CREATE CLUSTER,
      CREATE SYNONYM,
      CREATE PUBLIC SYNONYM,
      CREATE VIEW,
      CREATE MATERIALIZED VIEW,
      QUERY REWRITE
      TO VND;

ALTER SESSION SET CONTAINER = CDB$ROOT;

ALTER SYSTEM SET DB_KEEP_CACHE_SIZE = 2M SCOPE = MEMORY;

ALTER SESSION SET CONTAINER = VND_PDB;

ALTER USER VND QUOTA 5M ON TS_VND;

SELECT * FROM B_SYN_PUB;

--DROP USER VND;