CREATE GLOBAL TEMPORARY TABLE T_TEMP (ID NUMBER)
    ON COMMIT DELETE ROWS;
    
INSERT INTO T_TEMP VALUES (10);

SELECT * FROM T_TEMP;

COMMIT;

SELECT * FROM T_TEMP;

CREATE SEQUENCE S1
    INCREMENT BY 10
    START WITH 1000
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE
    NOORDER;
    
SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.CURRVAL FROM DUAL;

CREATE SEQUENCE S2
    INCREMENT BY 10
    START WITH 10
    MAXVALUE 100
    NOMINVALUE
    NOCYCLE
    NOCACHE
    NOORDER;

SELECT S2.NEXTVAL FROM DUAL;  
SELECT S2.CURRVAL FROM DUAL;

CREATE SEQUENCE S3
    INCREMENT BY -10
    START WITH -10
    NOMAXVALUE 
    MINVALUE -100
    NOCYCLE
    NOCACHE
    ORDER;
    
SELECT S3.NEXTVAL FROM DUAL;  
SELECT S3.CURRVAL FROM DUAL;

CREATE SEQUENCE S4
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 10 
    NOMINVALUE
    CYCLE
    CACHE 5
    NOORDER;
    
SELECT S4.NEXTVAL FROM DUAL;  
SELECT S4.CURRVAL FROM DUAL;

SELECT SEQUENCE_NAME FROM USER_SEQUENCES;

ALTER SEQUENCE S1 RESTART;
ALTER SEQUENCE S2 RESTART;
ALTER SEQUENCE S3 RESTART;
ALTER SEQUENCE S4 RESTART;

CREATE TABLE T1 (
    N1 NUMBER(20),
    N2 NUMBER(20),
    N3 NUMBER(20),
    N4 NUMBER(20)
);

ALTER TABLE T1 STORAGE (BUFFER_POOL KEEP);

INSERT INTO T1 VALUES (
    S1.NEXTVAL,
    S2.NEXTVAL,
    S3.NEXTVAL,
    S4.NEXTVAL
);

CREATE CLUSTER ABC (
    X NUMBER (10), 
    V VARCHAR2 (12)
) HASHKEYS 200;

CREATE TABLE A (
    XA NUMBER (10),
    VA VARCHAR2 (12),
    NAME VARCHAR2 (20)
) CLUSTER ABC (XA, VA);

CREATE TABLE B (
    XB NUMBER (10),
    VB VARCHAR2 (12),
    PRODUCT_ID VARCHAR2 (8)
) CLUSTER ABC (XB, VB);

CREATE TABLE C (
    XC NUMBER (10),
    VC VARCHAR2 (12),
    PHONE_NUMBER VARCHAR2 (15)
) CLUSTER ABC (XC, VC);

SELECT CLUSTER_NAME, TABLESPACE_NAME, HASHKEYS FROM USER_CLUSTERS;
SELECT TABLE_NAME, CLUSTER_NAME FROM USER_TABLES;
SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BYTES, BLOCKS, EXTENTS FROM USER_SEGMENTS;

CREATE SYNONYM C_SYN FOR VND.C;

SELECT * FROM C_SYN;

CREATE PUBLIC SYNONYM B_SYN_PUB FOR VND.B;

SELECT * FROM B_SYN_PUB;

CREATE TABLE STUDENTS (
    STUDENT_NAME VARCHAR2(20) PRIMARY KEY,
    MENTOR VARCHAR2(20)
);

CREATE TABLE MENTORS (
    MENTOR_NAME VARCHAR2(20) PRIMARY KEY,
    STUDENT VARCHAR2(20),
    CONSTRAINT FK_STUDENT
        FOREIGN KEY (STUDENT)
        REFERENCES STUDENTS(STUDENT_NAME)
);  

ALTER TABLE STUDENTS
ADD CONSTRAINT FK_MENTOR
FOREIGN KEY (MENTOR)
REFERENCES MENTORS (MENTOR_NAME);

INSERT INTO STUDENTS VALUES ('Nick', NULL);
INSERT INTO STUDENTS VALUES ('Andrey', NULL);

INSERT INTO MENTORS VALUES ('Dmitry', 'Nick');
INSERT INTO MENTORS VALUES ('Egor', 'Andrey');

UPDATE STUDENTS SET MENTOR = 'Dmitry' WHERE STUDENT_NAME = 'Nick';
UPDATE STUDENTS SET MENTOR = 'Egor' WHERE STUDENT_NAME = 'Andrey';
COMMIT;

CREATE VIEW V1 AS
    SELECT STUDENT_NAME, MENTOR, MENTOR_NAME, STUDENT FROM STUDENTS
        INNER JOIN MENTORS
        ON MENTOR_NAME = MENTOR;

SELECT * FROM V1;

CREATE MATERIALIZED VIEW MV_VND
    BUILD IMMEDIATE
    REFRESH COMPLETE
    NEXT SYSDATE + (2/1440)
    ENABLE QUERY REWRITE
    AS
        SELECT STUDENT_NAME, MENTOR, MENTOR_NAME, STUDENT FROM STUDENTS
            INNER JOIN MENTORS
            ON MENTOR_NAME = MENTOR;

SELECT * FROM MV_VND;

--DROP TABLE T_TEMP;
--DROP TABLE T1;
--DROP SEQUENCE S1;
--DROP SEQUENCE S2;
--DROP SEQUENCE S3;
--DROP SEQUENCE S4;
--DROP SYNONYM C_SYN;
--DROP SYNONYM B_SYN_PUB;
--DROP TABLE A;
--DROP TABLE B;
--DROP TABLE C;
--DROP MATERIALIZED VIEW MV_VND;
--DROP VIEW V1;
--ALTER TABLE STUDENTS DROP CONSTRAINT FK_MENTOR;
--ALTER TABLE MENTORS DROP CONSTRAINT FK_STUDENT;
--DROP TABLE STUDENTS;
--DROP TABLE MENTORS;
--DROP CLUSTER ABC;