ALTER SESSION SET CONTAINER=XEPDB1;

SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;

CREATE TABLESPACE VND_QDATA
    DATAFILE '/opt/oracle/oradata/XE/XEPDB1/VND_QDATA.dbf'
    SIZE 10M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 30M
    OFFLINE;
    
SELECT * FROM DBA_DATA_FILES;

ALTER TABLESPACE VND_QDATA ONLINE;
    
CREATE USER VND 
    IDENTIFIED BY pass
    DEFAULT TABLESPACE VND_QDATA
    ACCOUNT UNLOCK;
    
GRANT CREATE SESSION,
      CREATE TABLE
      TO VND;
      
ALTER USER VND QUOTA 5M ON VND_QDATA;

SELECT * FROM DBA_SEGMENTS WHERE SEGMENT_NAME = 'VND_T1';

SELECT * FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'VND_QDATA';

SELECT SEGMENT_NAME, EXTENTS, BLOCKS, BYTES FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'VND_QDATA';

SELECT * FROM DBA_SEGMENTS;

SELECT DISTINCT SEGMENT_TYPE FROM DBA_SEGMENTS;

SHOW PARAMETER DB_BLOCK_SIZE;

--DROP USER VND;
--DROP TABLESPACE VND_QDATA INCLUDING CONTENTS AND DATAFILES;