ALTER SESSION SET CONTAINER=CDB$ROOT;

SELECT PDB_NAME, PDB_ID, STATUS FROM DBA_PDBS;

CREATE PLUGGABLE DATABASE VND_PDB 
  ADMIN USER pdbadmin IDENTIFIED BY password
  FILE_NAME_CONVERT=('/opt/oracle/oradata/XE/pdbseed/','/opt/oracle/oradata/XE/VNDPDB/')
  STORAGE (MAXSIZE 2G);
  
ALTER SESSION SET CONTAINER=VND_PDB;  

SELECT FILE_NAME FROM CDB_DATA_FILES;
SELECT FILE_NAME FROM CDB_TEMP_FILES;
SELECT TABLESPACE_NAME FROM CDB_TABLESPACES;
SELECT ROLE FROM CDB_ROLES;
SELECT PRIVILEGE, GRANTEE FROM CDB_SYS_PRIVS;
SELECT PROFILE FROM CDB_PROFILES;
SELECT USERNAME FROM CDB_USERS;
SELECT GRANTEE, GRANTED_ROLE FROM CDB_ROLE_PRIVS;

ALTER SESSION SET CONTAINER=CDB$ROOT;

CREATE USER C##VND
   IDENTIFIED BY pass;
   
ALTER SESSION SET CONTAINER=VND_PDB;

CREATE USER C##VND
   IDENTIFIED BY pass;

GRANT CREATE SESSION TO C##VND CONTAINER = CURRENT;
GRANT CREATE TABLE TO C##VND;
ALTER USER C##VND QUOTA 2M ON SYSTEM;

ALTER SESSION SET CONTAINER=CDB$ROOT;

SELECT USERNAME FROM V$SESSION WHERE USERNAME IS NOT NULL;

--DROP TABLESPACE TS_VND INCLUDING CONTENTS AND DATAFILES;
--DROP TABLESPACE TS_VND_TEMP INCLUDING CONTENTS AND DATAFILES;
--DROP PLUGGABLE DATABASE VND_PDB
--  INCLUDING DATAFILES;
--DROP USER C##VND;