SELECT TABLESPACE_NAME, CONTENTS FROM DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_DATA_FILES;
SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_TEMP_FILES;

SELECT GROUP#, MEMBERS, BYTES, ARCHIVED, SEQUENCE#, STATUS, FIRST_CHANGE# FROM V$LOG;

SELECT GROUP#, MEMBER FROM V$LOGFILE;

ALTER SYSTEM SWITCH LOGFILE;

SELECT GROUP#, MEMBERS, THREAD#, SEQUENCE#, ARCHIVED, STATUS, FIRST_CHANGE# FROM V$LOG;

ALTER DATABASE ADD LOGFILE GROUP 4 '/opt/oracle/oradata/XE/redo041.log'
    SIZE 20M BLOCKSIZE 512;
    
SELECT GROUP#, MEMBERS, THREAD#, SEQUENCE#, ARCHIVED, STATUS, FIRST_CHANGE# FROM V$LOG;

ALTER DATABASE ADD LOGFILE MEMBER '/opt/oracle/oradata/XE/redo042.log' TO GROUP 4;
ALTER DATABASE ADD LOGFILE MEMBER '/opt/oracle/oradata/XE/redo043.log' TO GROUP 4;

SELECT GROUP#, MEMBER FROM V$LOGFILE;

ALTER DATABASE DROP LOGFILE MEMBER '/opt/oracle/oradata/XE/redo043.log';
ALTER DATABASE DROP LOGFILE MEMBER '/opt/oracle/oradata/XE/redo042.log';
ALTER DATABASE DROP LOGFILE GROUP 4;

SELECT GROUP#, MEMBER FROM V$LOGFILE;
SELECT GROUP#, MEMBERS, THREAD#, SEQUENCE#, ARCHIVED, STATUS, FIRST_CHANGE# FROM V$LOG;

--docker exec -t -i oracledb /bin/bash

SELECT NAME, LOG_MODE FROM V$DATABASE;
SELECT INSTANCE_NAME, ARCHIVER, STATUS FROM V$INSTANCE;
SELECT * FROM V$ARCHIVED_LOG;

--docker exec -it oracledb sqlplus / as sysdba  

ALTER SYSTEM SWITCH LOGFILE;

SELECT NAME, LOG_MODE FROM V$DATABASE;
SELECT INSTANCE_NAME, ARCHIVER, STATUS FROM V$INSTANCE;
SELECT * FROM V$ARCHIVED_LOG;

--docker exec -t -i oracledb /bin/bash

SELECT * FROM V$CONTROLFILE;

SHOW PARAMETER CONTROL;

--http://www.rebellionrider.com/how-to-read-control-file-in-oracle-database/